#!/usr/bin/env node
/**
 * Emits the token layer in the two shapes CSS cannot serve.
 *
 *   dist/tokens.json  — every token, both themes, with its category and the
 *                       comment that explains it. For a Figma sync, a native
 *                       app, a docs site, a script.
 *   dist/tokens.js    — the same data as a typed ES module, so a TypeScript
 *   dist/tokens.d.ts    consumer gets `TokenName` autocompletion instead of a
 *                       string it can typo.
 *
 * Generated from the CSS rather than hand-listed, for the same reason the
 * documentation site parses its own prop tables: a second copy of a list is a
 * copy that goes stale, and this one would go stale silently.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { extractTokens } from './extract-tokens.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = join(ROOT, 'dist')

const layers = extractTokens({
  tokens: join(ROOT, 'src', 'styles', 'tokens.css'),
  semantic: join(ROOT, 'src', 'styles', 'semantic.css'),
})

/** One record per token name: its light value, its dark value if it swaps. */
const tokens = {}
for (const [layer, sides] of Object.entries(layers)) {
  for (const entry of sides.light) {
    tokens[entry.name] = {
      layer,
      category: entry.category,
      light: entry.value,
      ...(entry.comment ? { comment: entry.comment } : {}),
    }
  }
  for (const entry of sides.dark) {
    if (tokens[entry.name]) tokens[entry.name].dark = entry.value
  }
}

mkdirSync(DIST, { recursive: true })
writeFileSync(join(DIST, 'tokens.json'), JSON.stringify(tokens, null, 2))

const names = Object.keys(tokens).sort()
writeFileSync(
  join(DIST, 'tokens.js'),
  `/* GENERATED by scripts/emit-tokens.mjs — do not edit. */\n` +
    `export const TOKENS = ${JSON.stringify(tokens, null, 2)}\n`,
)
writeFileSync(
  join(DIST, 'tokens.d.ts'),
  `/* GENERATED by scripts/emit-tokens.mjs — do not edit. */\n` +
    `export interface TokenRecord {\n` +
    `  /** Which CSS layer declared it: a primitive, or the role that names it. */\n` +
    `  layer: 'tokens' | 'semantic'\n` +
    `  /** Foundations grouping — colour, type, space, radius, motion, density… */\n` +
    `  category: string\n` +
    `  light: string\n` +
    `  /** Present only when the token swaps; absent means it holds in both themes. */\n` +
    `  dark?: string\n` +
    `  /** The comment above the declaration, which is usually the only place the reason is written. */\n` +
    `  comment?: string\n` +
    `}\n\n` +
    `export type TokenName =\n${names.map((name) => `  | '${name}'`).join('\n')}\n\n` +
    `export declare const TOKENS: Record<TokenName, TokenRecord>\n`,
)

console.log(`emit-tokens: ${names.length} tokens → dist/tokens.json, tokens.js, tokens.d.ts`)
