#!/usr/bin/env node
/**
 * Copies the three White Reset webfaces out of their @fontsource packages into
 * `src/styles/fonts/`, and regenerates `src/styles/fonts.css` to match.
 *
 * Why vendor at all: the token layer names its families through `var(--sans)`
 * etc., with literal fallbacks (`Hanken Grotesk`, `Newsreader`, `IBM Plex
 * Mono`). A host app that loads fonts itself — next/font, say — sets those
 * variables and never reaches the fallback. A standalone consumer has no such
 * variables, so these @font-face rules, declared under the EXACT fallback
 * family names, are what make the package render on-brand instead of in system
 * fonts.
 *
 * Why generated rather than hand-written: the weight list is the thing that
 * drifts. It is declared once, here, next to the files it copies, so adding a
 * weight cannot leave a rule pointing at a file nobody vendored.
 *
 * Latin subset only. The package's own surface is Latin; a consumer rendering
 * CJK supplies those faces through the --cjk-* variables, which is also the
 * only way to keep Google's ~400 unicode-range shards per family.
 */
import { copyFile, mkdir, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const OUT_DIR = join(ROOT, 'src', 'styles', 'fonts')
const CSS_OUT = join(ROOT, 'src', 'styles', 'fonts.css')

// Resolved rather than path-joined: pnpm isolates each package's dependencies
// under its OWN node_modules, so a hardcoded `../../node_modules` finds nothing
// here and would silently find the wrong copy in a hoisted layout.
const require = createRequire(import.meta.url)
const resolvePkgDir = (pkg) => dirname(require.resolve(`${pkg}/package.json`))

/**
 * `family` is the literal name the token layer falls back to; `pkg` is the
 * @fontsource directory; `file` is that package's latin file for the weight.
 */
const FACES = [
  { slug: 'hanken-grotesk', family: 'Hanken Grotesk', pkg: '@fontsource/hanken-grotesk', weights: [300, 400, 500, 600, 700] },
  { slug: 'newsreader', family: 'Newsreader', pkg: '@fontsource/newsreader', weights: [300, 400, 500, 600] },
  { slug: 'ibm-plex-mono', family: 'IBM Plex Mono', pkg: '@fontsource/ibm-plex-mono', weights: [400, 500, 600] },
]

const header = `/* GENERATED by scripts/vendor-fonts.mjs — do not edit by hand.
   Vendored Latin webfaces for @misoto22/design, declared under the literal
   family names the token layer falls back to. A host that loads these itself
   (next/font, a CDN) sets --font-* and never reaches these rules.
   Re-run: pnpm --filter @misoto22/design build:fonts */
`

async function main() {
  await mkdir(OUT_DIR, { recursive: true })
  const rules = [header]

  for (const face of FACES) {
    const written = []
    for (const weight of face.weights) {
      // @fontsource ships `files/<slug>-latin-<weight>-normal.woff2`.
      const src = join(resolvePkgDir(face.pkg), 'files', `${face.slug}-latin-${weight}-normal.woff2`)
      if (!existsSync(src)) {
        throw new Error(
          `Missing ${src}. Either the weight is not published for this family or ` +
            `the @fontsource layout changed; fix FACES in scripts/vendor-fonts.mjs.`,
        )
      }
      const name = `${face.slug}-${weight}.woff2`
      await copyFile(src, join(OUT_DIR, name))
      written.push({ weight, name })
    }

    rules.push(`\n/* ─── ${face.family} — ${written.length} weights ─── */`)
    for (const { weight, name } of written) {
      rules.push(
        `@font-face {\n` +
          `  font-family: '${face.family}';\n` +
          `  font-style: normal;\n` +
          `  font-weight: ${weight};\n` +
          `  font-display: swap;\n` +
          `  src: url('./fonts/${name}') format('woff2');\n` +
          `}`,
      )
    }
  }

  await writeFile(CSS_OUT, rules.join('\n') + '\n')
  const total = FACES.reduce((n, f) => n + f.weights.length, 0)
  console.log(`vendor-fonts: ${total} faces → src/styles/fonts/, rules → src/styles/fonts.css`)
}

await main()
